services:
  productsv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
      #postgresin konteyner içindeki veri depoladığı alan
    volumes:
     - productdb_vol:/var/lib/postgresql/data

  customersv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: customer_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - customerdb_vol:/var/lib/postgresql/data

  ordersv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - orderdb_vol:/var/lib/postgresql/data


volumes:
  productdb_vol: {}
  customerdb_vol: {}
  orderdb_vol: {}