server:
  port: 8085

spring:
  cloud:
    function:
      definition: orderCreatedConsumer;orderPaidConsumer;orderDeliveredConsumer;orderCancelledConsumer

    stream:
      defaultBinder: kafka
      bindings:
        orderCreatedConsumer-in-0:
          destination: order-created-events
          group: notification-service
          contentType: application/json

        orderPaidConsumer-in-0:
          destination: order-paid-events
          group: notification-service
          contentType: application/json

        orderDeliveredConsumer-in-0:
          destination: order-delivered-events
          group: notification-service
          contentType: application/json

        orderCancelledConsumer-in-0:
          destination: order-cancelled-events
          group: notification-service
          contentType: application/json

      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          orderCreatedConsumer-in-0:
            consumer:
              startOffset: earliest
          orderPaidConsumer-in-0:
            consumer:
              startOffset: earliest
          orderDeliveredConsumer-in-0:
            consumer:
              startOffset: earliest
          orderCancelledConsumer-in-0:
            consumer:
              startOffset: earliest

  datasource:
    url: jdbc:postgresql://localhost:5437/notification_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka