server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/order_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    function:
      # Order-service'te yazdığımız consumer bean isimleri:
      definition: stockDecreasedEvents;stockDecreaseFailedEvents
    stream:
      defaultBinder: kafka
      bindings:
        orderEvents-out-0:
          destination: order-events
          contentType: application/json

        stockDecreasedEvents-in-0:
          destination: stock-decreased-events
          group: order-service
          contentType: application/json

        stockDecreaseFailedEvents-in-0:
          destination: stock-decrease-failed-events
          group: order-service
          contentType: application/json

      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
